/* MeenLearn · lessons 1/3 — Programming (20) + HTML (20) */
window.MEEN_LESSONS_1 = {

  programming: [
    { t: "What is a program?",
      text: "A computer is unimaginably fast at doing exactly one thing: follow instructions, in order, exactly as written. A program is that list of instructions. There is no guessing and no common sense — if you say add twice, it adds twice, or a million times if you put it in a loop. Learning to program is mostly learning to be precise.",
      def: "A program is a precise, ordered list of instructions that a computer can execute without any interpretation or common sense.",
      code: "RECIPE (not code, yet):\n1. take 2 eggs\n2. crack them into a bowl\n3. whisk for 30 seconds\n4. cook in a pan\n\nNotice: every step is specific and\nin order. A program is the same idea\n— just written for a machine.",
      out: { term: "You:    make coffee\nCode:   boil water\n        add grounds\n        pour slowly\n        repeat until empty\n\nEvery program is a recipe.\nThe computer just never guesses." },
      flow: ["You write steps", "Computer reads", "Follows exactly", "Gives result"],
      task: "Write the algorithm for making toast in 5 numbered steps, precise enough that a robot could follow it without asking you a single question.",
      mistake: "Writing steps that rely on judgment: \"cook until nice\". A machine can't evaluate \"nice\" — every step must be checkable: temperature, time, or a yes/no condition.",
      tip: "Programs fail in two ways: wrong steps, or steps in the wrong order. When something breaks, check the order first — it's the most common mistake.",
      challenge: "Write an algorithm to wash one shirt by hand. Then find one step where your instructions are ambiguous and fix it." },

    { t: "Algorithms: problems become steps",
      text: "An algorithm is a step-by-step method for solving a problem — the plan before the code. You've been writing one since lesson 1; now we do it deliberately. Good habit: never open the editor until the algorithm is on paper. If the plan is wrong, no amount of coding fixes it.",
      def: "An algorithm is a finite, ordered set of steps that transforms input into output.",
      code: "PROBLEM: find the largest of 3 numbers\n\nALGORITHM:\n1. take the 1st number, call it best\n2. if number 2 is bigger than best,\n   best becomes number 2\n3. if number 3 is bigger than best,\n   best becomes number 3\n4. answer: best\n\nWorks for ANY 3 numbers. That's the point.",
      out: { term: "Input:  7, 12, 4\n\nStep 1: best = 7\nStep 2: 12 > 7  -> best = 12\nStep 3: 4 > 12? no\nStep 4: answer 12\n\nSame steps, new input 1, 2, 3:\nanswer = 3. One plan, every case." },
      flow: ["Problem", "Input", "Steps", "Output"],
      task: "Write the algorithm to find the average of any list of numbers. Test it in your head with [10, 20] and with [5].",
      mistake: "Solving one specific example instead of the general problem (\"add 7 and 12\" instead of \"add two numbers\"). Ask yourself: would my steps still work if the input were bigger, smaller, or zero?",
      tip: "Name your steps like a story: start, compare, update, repeat, finish. If you can narrate the algorithm out loud smoothly, it's probably correct.",
      challenge: "Write an algorithm to check if a 3-digit number is a palindrome (reads the same forwards and backwards), e.g. 121." },

    { t: "Data: the stuff programs handle",
      text: "Every program exists to manipulate data — and data is just information stored in some form. Your program's job is always: receive data, process it, produce data. Before writing logic, list what data your program touches. This one habit prevents most \"wait, where did this value come from?\" confusion.",
      def: "Data is any piece of information a program stores or manipulates: numbers, text, yes/no facts, or collections of these.",
      code: "PROBLEM: a tip calculator\n\nDATA it touches:\n  bill:   45        (a number)\n  tip%:   10        (a number)\n  total:  49.5      (computed)\n  note:   \"thanks!\" (text)\n\nThe logic is trivial once the\ndata is listed.",
      out: { term: "bill  = 45\ntip%  = 10\ntotal = 45 + (45 * 0.10)\n      = 45 + 4.5\n      = 49.5\n\nProgram = steps + data.\nNo data, no program." },
      flow: ["Data in", "Processing", "Data out"],
      task: "For a \"show the weather\" program, list every piece of data it would need (temperature, city, units...) and say which come from the user and which are computed.",
      mistake: "Starting with logic before knowing the data. You can't process what you haven't named — if you can't list your data, you don't yet understand the problem.",
      tip: "Ask three questions for every program: What data comes IN? What data comes OUT? What data exists only INSIDE while working? That's your whole design.",
      challenge: "Design the data for a contact book program: what does one contact contain, and what data does the program need to add, find and delete contacts?" },

    { t: "Input, processing, output",
      text: "The IPO model is the shape of every program: Input (something comes in), Processing (the steps transform it), Output (something goes out). A calculator: input 2, 3, +; processing adds; output 5. A website: input your clicks; processing updates the page; output the new screen. When you're stuck, draw the three boxes.",
      def: "IPO is the universal program structure: data enters (Input), is transformed by steps (Processing), and results leave (Output).",
      code: "PROBLEM: show a greeting with the\nuser's name\n\nINPUT:      name typed by user\nPROCESSING: build the sentence\n            \"Hello, \" + name\nOUTPUT:     the sentence on screen\n\nThree boxes. Every program fits.",
      out: { term: "INPUT:      \"Ada\"\nPROCESSING: \"Hello, \" + \"Ada\"\nOUTPUT:     \"Hello, Ada\"\n\nChange the input to \"Moa\":\nOUTPUT:     \"Hello, Moa\"\n\nSame processing, new output." },
      flow: ["Input", "Processing", "Output"],
      task: "Draw the IPO boxes for a program that takes a temperature in Celsius and shows it in Fahrenheit (F = C × 9/5 + 32).",
      mistake: "Forgetting that output must come from the processing, not appear magically. If you can't say \"this output was produced by this step\", there's a hole in your logic.",
      tip: "Real programs are usually chains of IPO: the output of one box becomes the input of the next. Seeing the chain makes big problems small.",
      challenge: "Design IPO for a program that reads three test scores and outputs the average plus a grade (A if ≥ 90, B if ≥ 80, C otherwise). What extra data does the processing need?" },

    { t: "Variables: named boxes for values",
      text: "A variable is a named box that holds a value. When you write age = 21, you're putting 21 in a box labeled age. Later you write age = 22, and the box now holds 22 — the old value is gone. The name is a label, not the value itself. This single idea — names pointing at changeable values — is the foundation of all programming.",
      def: "A variable is a named storage location that holds a value, which can be read, changed, and referenced anywhere in the program.",
      code: "score = 0\nscore = 10\nscore = score + 5\n\n# what is score now?\n\nLine 1: box 'score' holds 0\nLine 2: box now holds 10 (0 gone)\nLine 3: read 10, add 5, store 15\n\nAnswer: 15",
      out: { term: "score  [ 0 ]\nscore  [ 10 ]\nscore  [ 15 ]   <- 10 + 5\n\nA variable is a box with a label.\nThe label stays; the value changes." },
      flow: ["Name a box", "Put a value in", "Read it", "Change it"],
      task: "Trace this on paper: total = 5, then total = total * 2, then total = total + 3. What is total at the end? (Answer in the quiz — write it down first.)",
      mistake: "Thinking of x = 5 as \"x is 5 forever\". The box metaphor is why: the label x is fixed, the contents are replaceable. Most \"why is my value wrong?\" bugs come from forgetting something reassigned the box.",
      tip: "Name variables for humans: totalScore, userName, isReady — not a, b, x. Future-you debugging this at midnight will be grateful.",
      challenge: "Trace: a = 3, b = 7, a = b, b = a. What are a and b now? (Trick: two boxes, two assignments — step through one line at a time.)" },

    { t: "Data types: numbers, text, truth",
      text: "Values come in types, and the type decides what operations make sense. Numbers support math; text supports joining; booleans (true/false) support decisions. Mixing types accidentally is one of the most common beginner bugs: adding the text \"5\" to the number 3 doesn't give 8 — it glues the strings together and gives \"53\".",
      def: "A data type is the category of a value (number, text, boolean...) that determines what operations are allowed on it.",
      code: "number:   42, 3.5, -7\nstring:   \"hello\", \"5\" (quoted!)\nboolean:  true, false\n\n42 + 8      -> 50      (math)\n\"5\" + \"3\"   -> \"53\"    (gluing text)\n5 == 5      -> true\n\nThe quotes change the type.",
      out: { term: "type of 42     -> number\ntype of \"42\"   -> string\ntype of true   -> boolean\n\n42 + 8     = 50\n\"42\" + 8   = \"428\"  (glued!)\n\nSame symbols, different types,\ntotally different results." },
      flow: ["Value", "has a type", "type allows", "operations"],
      task: "Predict, then verify: what does \"3\" * 4 give in most languages? (Hint: in JavaScript it repeats the text: \"333\". In Python it's an error.)",
      mistake: "Treating text and numbers as interchangeable. \"7\" (text) and 7 (number) look identical but behave differently in math, comparisons, and storage. Convert explicitly when you need to.",
      tip: "When a calculation gives a weird result, check the types of every input first — 9 times out of 10 the culprit is a string sneaking into math.",
      challenge: "A program reads age from the user (always as text) and computes age + 1. What's wrong, and how do you fix it in one step?" },

    { t: "Making decisions: if / else",
      text: "Programs choose paths with conditions — questions that are yes or no. If the condition is true, one block runs; otherwise the else block runs. Exactly one path is taken, never both. This is how programs react: if score >= 50, say \"pass\"; otherwise, say \"retry\". You can chain several (if / else if / else) or combine questions with AND, OR and NOT.",
      def: "A conditional (if/else) executes one of two code blocks depending on whether a boolean condition is true or false.",
      code: "score = 42\n\nif score >= 50:\n    show \"pass\"\nelse:\n    show \"retry\"\n\n# only ONE branch ever runs.\n\nCombine conditions:\nif score >= 50 AND score <= 100:\n    show \"valid score\"",
      out: { term: "score = 42\n42 >= 50 ?  no\n-> else runs\n-> screen: \"retry\"\n\nscore = 87\n87 >= 50 ?  yes\n-> if runs\n-> screen: \"pass\"" },
      flow: ["Ask a yes/no question", "Yes?", "run path A", "No? run path B"],
      task: "Write the condition logic for a door that opens only if the person is a member AND has paid this month. How do you test it without a computer? (Try: member=paid, member=unpaid, etc.)",
      mistake: "Forgetting that a condition must be a yes/no question. if score: (a bare value) is wrong in most languages — you need if score > 50: or similar. And exactly one branch runs; if you need two independent checks, write two ifs, not an else.",
      tip: "When chaining conditions, order matters: check the rarest or cheapest case first. And for ranges, remember AND: if 0 <= x <= 100 (or the two-part form) — one side alone is not a range.",
      challenge: "Design the conditions for a pricing rule: under 10 items = full price, 10–49 = 5% off, 50+ = 15% off. Write it as if / else if / else in plain words." },

    { t: "Loops: repeating work",
      text: "No human wants to write the same line 1,000 times — loops do it for you. A for-loop repeats a fixed number of times (or over each item in a list); a while-loop repeats as long as a condition stays true. The classic bug is a loop that never ends: you forgot to change something inside, so the condition is true forever.",
      def: "A loop repeatedly executes a block of code — either a set number of times (for) or while a condition holds (while).",
      code: "FOR: repeat a known number of times\nfor i from 1 to 5:\n    show \"lap \" + i\n\nWHILE: repeat as long as true\nwater = 8          # glasses left\nwhile water > 0:\n    drink one glass\n    water = water - 1\n\nThat last line is what lets it end.",
      out: { term: "lap 1\nlap 2\nlap 3\nlap 4\nlap 5\n(ends — i reached 5)\n\n---\nwater: 8,7,6,5,4,3,2,1,0\n(ends — condition false)" },
      flow: ["Condition?", "True? -> run body", "Update something", "Ask again"],
      task: "Write a while-loop (in plain steps) that counts down from 10 to 0, then prints \"liftoff\". Where does the \"count down\" step have to happen, and what happens if you forget it?",
      mistake: "An infinite while-loop: the condition depends on a value that never changes inside the body. Symptom: the program hangs. Fix: make sure the body moves the condition toward false.",
      tip: "Every loop answers three questions: what starts it (initial state), what changes each pass (update), what ends it (exit condition). If you can answer all three, the loop is sound.",
      challenge: "Write the steps for a loop that prints all even numbers from 2 to 20. Then modify it to stop at 10 — which of your three loop questions changed?" },

    { t: "Functions: reusable step blocks",
      text: "A function is a named, reusable block of steps. You define it once and call it anywhere — the code lives in one place. Functions take inputs (parameters) and usually hand back a result (return). They're the core tool for readable code: if you find yourself copying the same block twice, it wants to be a function.",
      def: "A function is a named unit of code that can be called multiple times, takes parameters as input, and returns a result as output.",
      code: "DEFINE add(a, b):\n    RETURN a + b\n\nadd(2, 3)  -> 5\nadd(10, 20) -> 30\n\nThe recipe is written ONCE,\nused ANY number of times.\n\nParameters are the slots (a, b);\narguments are the values you put in.",
      out: { term: "add(2,3):  a=2, b=3\n  return 2+3 = 5\n\nadd(10,20): a=10, b=20\n  return 10+20 = 30\n\nOne definition, infinite calls.\nEach call gets fresh values." },
      flow: ["Define once", "Call with inputs", "Runs the steps", "Returns result"],
      task: "Define a function in plain words that takes a radius and returns the area of a circle (use 3.14 as pi). Call it with radius 2 — what does it return?",
      mistake: "Forgetting RETURN. A function without return does its work but hands back nothing — the caller gets an empty answer and the bug hides until you print the result. If a function is supposed to give an answer, it must return one.",
      tip: "Good function names are verbs: addTotal, findLargest, isMember. The name should let you use the function without ever opening its body.",
      challenge: "Design a function that takes three numbers and returns how many of them are positive. What should it return for [0, 5, -2]?" },

    { t: "Parameters and return values",
      text: "Parameters are the function's input slots; arguments are the actual values you pass in. Return is how the function hands its answer back — and the moment RETURN runs, the function stops. Understanding this flow is what turns \"functions are mysterious\" into \"functions are just reusable sub-programs with an answer\".",
      def: "Parameters are the named inputs a function expects; the return statement sends a result back to the caller and ends the function.",
      code: "DEFINE power(base, exp):\n    result = 1\n    REPEAT exp times:\n        result = result * base\n    RETURN result\n\npower(2, 3):\n  base=2, exp=3\n  result: 1 -> 2 -> 4 -> 8\n  RETURN 8\n\npower(2, 3) + power(2, 2) = 8 + 4 = 12",
      out: { term: "power(2,3):\n  pass 1: result = 1*2 = 2\n  pass 2: result = 2*2 = 4\n  pass 3: result = 4*2 = 8\n  -> returns 8\n\npower(2,3) + power(2,2)\n= 8 + 4 = 12\n\nReturned values can feed other\ncalls. That's composition." },
      flow: ["Call with arguments", "Arguments fill parameters", "Body runs", "RETURN stops & answers"],
      task: "Define a function (in steps) that takes a number and returns it doubled, but only if it's even; otherwise return it unchanged. What does it return for 7 and for 8?",
      mistake: "Confusing the parameter name with the argument: if the function is max(a, b), calling max(9, 4) doesn't make the number 9 \"a\" — a is just the slot name, a label for the first value. Mix-ups here cause baffling wrong results.",
      tip: "A function can have several RETURNs (one per branch) but only one ever runs in a single call. That's how if/else inside functions produces different answers.",
      challenge: "Why does this return nothing useful? f(x): return x + 1 ; show \"done\" — where does execution go after RETURN, and what does the caller receive?" },

    { t: "Lists: many values in one name",
      text: "A list (or array) is an ordered collection of values under one name: [\"apple\", \"banana\", \"cherry\"]. You reach items by position — the index — and in almost every language the first item is index 0, not 1. That's the famous \"arrays start at zero\" fact, and it's the #1 source of off-by-one bugs in loops.",
      def: "A list is an ordered collection of values, accessed by position (index), starting at 0 in most languages.",
      code: "fruits = [\"apple\", \"banana\", \"cherry\"]\n\nfruits[0]  -> \"apple\"     <- first!\nfruits[1]  -> \"banana\"\nfruits[2]  -> \"cherry\"\n\nlen(fruits) -> 3\n\nLoop over a list:\nfor fruit in fruits:\n    show fruit",
      out: { term: "index:  0      1       2\n       [apple][banana][cherry]\n\nfruits[0] = \"apple\"\n\nLoop:\n  show apple\n  show banana\n  show cherry" },
      flow: ["Store many values", "Order matters", "Index from 0", "Loop over all"],
      task: "You have scores = [70, 85, 60, 95]. Write the steps to find the highest score using a loop and a best-so-far variable. What is the answer?",
      mistake: "Off-by-one: looping \"from 0 to 3\" when the list has 4 items (or vice versa) because you mixed up count and last index. The last index is length − 1. When in doubt, prefer the \"for each item\" form of loop, which has no indices at all.",
      tip: "A list is how you scale: instead of score1, score2, score3... variables, one scores list plus a loop handles 3 or 3,000 items. If you catch yourself writing variable2, variable3 — you want a list.",
      challenge: "Write the steps to reverse a list by hand (first becomes last). What's the trick for lists with an odd number of items — what happens to the middle element?" },

    { t: "Dictionaries: data with labels",
      text: "A dictionary (or map/object) stores values under named keys instead of positions: { \"name\": \"Ada\", \"age\": 36 }. Look up by label: user[\"age\"]. Real programs are built mostly from these: a user profile, a database row, a JSON file, a config — all families of labeled values. Where a list answers \"which item?\", a dictionary answers \"which label?\"",
      def: "A dictionary is a collection of key-value pairs — values looked up by name (key) rather than position (index).",
      code: "user = {\n  \"name\": \"Ada\",\n  \"age\": 36,\n  \"admin\": true\n}\n\nuser[\"name\"]  -> \"Ada\"\nuser[\"age\"]   -> 36\n\nAdd a key:   user[\"city\"] = \"London\"\nCheck:       \"email\" in user  -> false\n\nLists: by position. Dictionaries: by label.",
      out: { term: "user = {\n  name: Ada\n  age: 36\n  admin: true\n}\n\nuser[\"age\"]  -> 36\nuser[\"city\"] -> not found (yet)\nuser[\"city\"] = \"London\"\nuser[\"city\"] -> \"London\"" },
      flow: ["Value has a key", "Store pairs", "Look up by label", "Add/update keys"],
      task: "Build (in words or pseudocode) a dictionary for a book: title, author, pages, read (true/false). Then look up the author and mark it as read.",
      mistake: "Looking up a key that might not exist and crashing (or getting \"nothing\") when it's missing. Check membership first, or use a \"get with default\" form if your language has one.",
      tip: "If you find yourself maintaining parallel lists — names = [...], ages = [...] — merge them into one dictionary. One key, one place, no index sync bugs.",
      challenge: "Why can't a list be a dictionary's key in most languages (hint: keys must be unique and stable, and lists can change)? What would you use instead?" },

    { t: "Errors and debugging",
      text: "Errors are information, not failure. The debug loop: run → read the error → guess the cause → fix → run again. Read error messages from the bottom: the last line usually names the problem, and the lines above show where it happened. Add print statements to reveal what variables actually hold — seeing real values beats guessing every time.",
      def: "Debugging is the repeat cycle of running code, reading the error, forming a hypothesis about the cause, fixing, and re-running.",
      code: "The loop:\n  RUN -> SEE ERROR -> GUESS\n  -> FIX -> RUN again\n\nRead bottom-up:\n  Error: line 7, 'x' not defined\n\nGuess:  I spelled the variable\n  wrong on line 7 (x vs myX).\n\nProof:  print the variable around\n  line 7. See the real value.\n\nNever debug from memory — always\nre-run after changing anything.",
      out: { term: "Error on line 7:\n  total = toatl + 1\n\nBottom line: toatl unknown\nHypothesis:  typo in the name\nFix:         total = total + 1\nRe-run:      works\n\nThe error was a gift:\nit named the exact problem." },
      flow: ["Run", "Read error (bottom-up)", "Hypothesize", "Fix + re-run"],
      task: "Take any 10-line algorithm you've written this week and insert a deliberate bug (wrong variable name, or an off-by-one). Can you find it using only the error message and one print statement?",
      mistake: "Fixing the first thing that looks wrong instead of the thing the error names. Errors are precise about location; your guesses are not. Trust the message, verify with a print, then change one thing at a time.",
      tip: "If you change three things and it suddenly works, you don't actually know which one fixed it — and you've planted two unknown changes. Fix one thing per run.",
      challenge: "This loop never prints: i = 0; while i < 5: show i; i = i + 1 — wait, it should print. Now make it a bug: which single change (i = 0 → i = 10, or i = i - 1) produces an infinite loop vs. a silent one, and how would you tell from the behavior?" },

    { t: "Pseudocode: logic before syntax",
      text: "Pseudocode is the algorithm written in loose, plain-English steps, ignoring exact syntax. It lets you validate the logic while the syntax of any specific language gets in the way. Rule: if you can't write the pseudocode, you don't understand the problem yet — and no amount of typing will fix that.",
      def: "Pseudocode is a language-agnostic, plain-English description of an algorithm's steps, used to design and verify logic before coding.",
      code: "PROBLEM: keep asking for a number\nuntil the user enters 0\n\nPSEUDOCODE:\n1. REPEAT:\n2.   ask \"enter a number\"\n3.   read the answer\n4. UNDONE until the answer is 0\n5. show \"you quit!\"\n\nNo language keywords. Pure logic.\nTranslate to any language later.",
      out: { term: "Run 1:  enter 7  -> loop\nRun 2:  enter 3  -> loop\nRun 3:  enter 0  -> stop\n\n\"you quit!\"\n\nSame pseudocode becomes valid\nPython, JS, or any language —\nthe logic is portable." },
      flow: ["Write steps in English", "Check the logic", "Translate to a language", "Code the real thing"],
      task: "Write pseudocode for: \"find the second-highest score in a list\". (Don't code it — just steps. Hint: it's not the same as removing the max and taking the new max. Why?)",
      mistake: "Writing pseudocode that secretly contains syntax (\"for i in range: \") — that's half-coded, half-planned, and gets the worst of both. Keep it at the logic level: repeat, ask, check, stop.",
      tip: "Read your pseudocode out loud, slowly, like a story. Wherever you stumble or say \"and then, um...\", that's a gap in the logic. Fix the story before you write code.",
      challenge: "Translate this pseudocode into steps in words, then spot the flaw: \"1. for each number: 2. if bigger than max, max = number\" — what's missing that makes the answer always wrong for lists like [9, 1, 5]?" },

    { t: "Flowcharts: logic you can see",
      text: "A flowchart draws the algorithm: boxes for steps, diamonds for decisions (yes/no exits), arrows for the direction of flow. It's the same logic as pseudocode but spatial — and seeing the arrows makes missing branches obvious. Every decision diamond must have two exits; if one path leads nowhere, your logic has a hole.",
      def: "A flowchart is a diagram of an algorithm using standard shapes: rectangles (steps), diamonds (decisions), and arrows (control flow).",
      code: "START\n  |\n  v\n[ read a number ]\n  |\n  v\n< is it even? >\n  /      \\\n yes      no\n  |        |\n  v        v\n[ show     [ show\n \"even\" ]   \"odd\" ]\n  \\        /\n   \\      /\n    [ END ]\n\nTwo exits from the diamond.\nBoth lead somewhere.",
      out: { term: "Input 4:  even? yes  -> \"even\" -> END\nInput 7:  even? no   -> \"odd\"  -> END\n\nSee the whole logic in one glance.\nA missing arrow = a missing branch." },
      flow: ["Start", "Steps (boxes)", "Decisions (diamonds)", "End"],
      task: "Draw (on paper or in words) a flowchart for: \"repeat until the user enters their name; if it's empty, ask again.\" How many decision diamonds do you need?",
      mistake: "A decision diamond with only one outgoing arrow. Every yes/no question has two answers — drawing both forces you to handle the case you'd otherwise forget (the \"no\" path is where most bugs live).",
      tip: "If your flowchart has arrows crossing everywhere, your logic probably has nested decisions that could be flattened into a simpler if/else chain. Clean arrows, clean code.",
      challenge: "Draw a flowchart for finding the max of a list. How does the \"for each item\" loop look as arrows, and where does the base case (an empty list) break the chart?" },

    { t: "Recursion: functions that call themselves",
      text: "Recursion is a function that calls itself with a smaller version of the problem, until it reaches a base case it can answer directly. Two rules: always have a base case, and always shrink the problem. Break either rule and the calls pile up forever — a crash instead of an answer.",
      def: "Recursion is solving a problem by calling the same function on a smaller sub-problem, until a base case stops the chain.",
      code: "countdown(n):\n  if n == 0:          # base case\n    show \"liftoff!\"\n    return\n  show n\n  countdown(n - 1)    # smaller problem\n\ncountdown(3):\n  show 3\n  countdown(2):\n    show 2\n    countdown(1):\n      show 1\n      countdown(0):\n        show \"liftoff!\"",
      out: { term: "3\n2\n1\nliftoff!\n\nEach call waits for the next\nsmaller call to finish.\nBase case (n=0) stops the chain." },
      flow: ["Call with big problem", "Do one step", "Call self with smaller", "Base case stops it"],
      task: "Write a recursive function (in words) that adds up the numbers from 1 to n: sumTo(1)=1, sumTo(n)= n + sumTo(n-1). What is sumTo(4)?",
      mistake: "No base case (calls forever, then crashes with \"too many calls\") or not shrinking (countdown(n) calls countdown(n) — same size, no progress). Check both rules before running anything recursive.",
      tip: "When reading recursive code, don't trace all the way down — trust that the smaller call works, and just check: base case correct? problem actually smaller? Those two checks are 95% of recursion debugging.",
      challenge: "Why does this crash? fact(n): return n * fact(n-1) — what's missing, and what's the base case for fact(0)? (Hint: the answer is a famous number.)" },

    { t: "Trace tables: running code on paper",
      text: "A trace table runs the code by hand: one row per loop pass, one column per variable, writing each value after every line. It feels slow at first, then it becomes your superpower — off-by-one bugs and mystery values die on paper before they ever reach the computer.",
      def: "A trace table is a manual execution of code, recording every variable's value after each step, used to predict output and find logic bugs.",
      code: "Code:\n  total = 0\n  for i in [3, 5, 2]:\n      total = total + i\n\nTrace table:\n  i      total\n  --     ----\n  3       0+3  = 3\n  5       3+5  = 8\n  2       8+2  = 10\n\nFinal: total = 10\nNo computer needed.",
      out: { term: "start:  total = 0\npass 1: i=3, total=3\npass 2: i=5, total=8\npass 3: i=2, total=10\n\nPredicted output: 10\nMatches the real run?\nYes -> logic is sound.\nNo  -> the bug is on paper." },
      flow: ["List variables", "One row per step", "Write values", "Compare to reality"],
      task: "Trace this: x = 4; for i in range(3): x = x * 2. What is x at the end? (Write the table before you peek.)",
      mistake: "Tracing \"what the code should do\" instead of \"what it actually says\". Copy the code exactly, including the off-by-one you're trying to catch — the table only works if it mirrors reality line by line.",
      tip: "For loops, trace one extra row past the end: what happens when the last item is processed? That's where the \"runs one time too many/few\" bugs always live.",
      challenge: "Here's a table: pass 1: i=0, count=1; pass 2: i=1, count=3; pass 3: i=2, count=5. What code produces it (hint: count starts at 0 and adds something each pass), and what would pass 4 give if the list had 4 items?" },

    { t: "Testing your thinking",
      text: "Testing means checking that your code behaves as you expect: given input X, output must be Y. Start by hand (trace tables, edge cases), then write small automated checks. The real skill is choosing test cases: empty input, one item, zero, negatives, the boundary value. Bugs live at the edges, not in the middle.",
      def: "Testing is systematically checking a program's output against expected results for chosen inputs, especially edge cases.",
      code: "Function: isAdult(age) -> age >= 18\n\nTest cases (input -> expected):\n  18   -> true    (boundary!)\n  17   -> false   (just below)\n  0    -> false\n  120  -> true\n  -5   -> false?  (edge: invalid\n                  input - decide!)\n\n5 tests, 2 lines of logic.\nThe boundary (18) is the star.",
      out: { term: "isAdult(18)  -> true   pass\nisAdult(17)  -> false  pass\nisAdult(0)   -> false  pass\nisAdult(120) -> true   pass\n\nAll pass -> high confidence.\nOne fail -> exact bug location." },
      flow: ["Pick inputs (edges!)", "Predict output", "Run", "Compare"],
      task: "For a function that splits a list into evens and odds, write 4 test cases including at least one edge. What does it do for an empty list, and for a list with one item?",
      mistake: "Only testing the happy middle (age=30) and never the edges (0, 17, 18, negative). The middle works in almost every program; the edges are where it breaks. Every boundary deserves a test.",
      tip: "Write the test first, then the code. It forces you to define \"correct\" before you define \"done\" — and you can't accidentally write code that passes a test you never thought to write.",
      challenge: "A price function has a bug: 9 items cost full price, but 10 items cost MORE than 9 (the discount threshold is off by one). Design the two test cases that would have caught it before release." },

    { t: "Complexity: fast vs slow",
      text: "Not all solutions are equally fast. Checking one value is constant time; scanning a list of n items is linear; scanning every pair of items is quadratic. You don't need the math — just the habit of asking \"how many times does the inner loop run?\" 1,000 items is fine for pairs (a million checks); 100,000 items is not (ten billion).",
      def: "Computational complexity describes how a program's work grows as the input grows — constant, linear (n), or quadratic (n²) being the common shapes.",
      code: "CONSTANT: check first item      -> 1 step\nLINEAR:   scan a list of n       -> n steps\nQUADRATIC: check every pair      -> n x n steps\n\nn = 1,000\n  linear:    1,000 steps\n  quadratic: 1,000,000 steps\n\nn = 100,000\n  linear:    100,000\n  quadratic: 10,000,000,000  <- slow\n\nAsk: how many times does the\ninner loop run?",
      out: { term: "Input size n      linear    quadratic\n      10            10        100\n      100           100       10,000\n      1,000         1,000     1,000,000\n      10,000        10,000    1,000,000,000\n\nDoubling input: linear doubles,\nquadruples the work. That's the gap." },
      flow: ["Input grows", "Count the work", "Constant? linear? n²?", "Choose the faster plan"],
      task: "You need to check if a list has duplicates. Plan A: compare every pair. Plan B: sort, then check neighbors. Which is faster for n = 10,000, and why (roughly)?",
      mistake: "Assuming a solution that works at n=100 will work at n=1,000,000. Growth rate matters more than current speed — a quadratic solution that takes 1 second at 1,000 items takes ~10,000 seconds (3 hours) at 1,000,000.",
      tip: "When reviewing code (yours or someone else's), count nested loops: one loop = linear, two nested = quadratic. That single habit explains most \"why is this slow\" questions.",
      challenge: "A function scans a list to find the max (linear), then scans again to find its position (linear again). Is the whole thing still linear? Why or why not — what makes two linear passes different from one nested pair?" },

    { t: "Putting it all together: build a program",
      text: "Time to combine everything: data, variables, types, decisions, loops, functions, lists and dictionaries — into one small program you design yourself. The method: (1) write the data, (2) write the IPO, (3) write the algorithm in pseudocode, (4) spot the loops and the functions, (5) trace one pass, (6) only now, write it in a real language.",
      def: "Designing a program end-to-end: data first, then IPO, then pseudocode, then structure (loops/functions), then a trace, then real code.",
      code: "PROJECT: a simple score tracker\n\n1. DATA:   scores (list), name (text)\n2. IPO:    IN: new score  PROC: add,\n           compute avg  OUT: name + avg\n3. PSEUDO: repeat: read score, add to\n           list; on stop, show\n           name and average\n4. STRUCT: loop for input, function\n           for average\n5. TRACE:  one pass with 2 scores\n6. CODE:   now, in any language\n\nSix steps. Zero mystery.",
      out: { term: "name: Ada\nscores: [ ]\nenter 80 -> [80]\nenter 90 -> [80,90]\nstop -> average = 85\n\n\"Ada: 85\"\n\nEvery tool from the track,\nin one small program." },
      flow: ["Data", "IPO", "Pseudocode", "Structure", "Trace", "Code"],
      task: "Apply the 6 steps to this project: \"a program that takes a list of temperatures and shows the highest, the lowest, and the average.\" Write steps 1-5 before touching any code.",
      mistake: "Skipping to step 6 (code) when stuck — but the bug is almost always in steps 2-4, invisible until you write them down. If you can't write the pseudocode, you haven't solved the problem yet.",
      tip: "When a project feels big, find the smallest version that still uses everything (a list + a loop + a function). Build that, then add features one at a time. Big projects are small projects stacked.",
      challenge: "Add a feature to the score tracker: after each new score, show a message if the new score beat the previous average. Which step of the 6 changes first, and why?" }
  ],

  html: [
    { t: "What HTML is and how the browser reads it",
      opt: ["vscode"],
      text: "HTML (HyperText Markup Language) is the structure of a web page — the headings, paragraphs, links and images, arranged in nested elements. It is not a programming language: there are no loops and no variables, only a tree of labeled boxes. You write it in a plain text file, and the browser reads it top to bottom, building a tree it can paint on screen.",
      def: "HTML is the markup language that defines a page's content and structure as nested elements, which the browser parses into a tree and renders.",
      code: "<h1>My page</h1>\n<p>Hello, world</p>\n\nWhat you write (text)   ->  what\nthe browser builds (tree) ->  what\nthe user sees (rendered page)\n\nHTML = structure. No logic,\nno style — that's CSS and JS.",
      out: { web: { h: "<h1 style=\"font-family:Georgia\">My page</h1><p style=\"font-family:sans-serif\">Hello, world</p>", c: "body{background:#fff;padding:20px}", j: "" } },
      flow: ["You write tags", "Browser parses", "Builds a tree", "Paints the page"],
      task: "Open any website, right-click → \"View page source\". Find the <h1>, a <p>, and a link. What does each contain?",
      mistake: "Thinking of HTML as a programming language. There are no if-statements or loops in HTML — it's a list of elements. The \"logic\" (reactions, data) comes from JavaScript later.",
      tip: "HTML files are just text. Save one as page.html and double-click it — it opens in your browser. That's the whole toolchain for today.",
      challenge: "Write an HTML file with a heading, two paragraphs, and a link to a MeenLearn page. Open it, then break one closing tag on purpose — what does the browser do?" },

    { t: "The document skeleton (doctype, html, head, body)",
      text: "Every HTML page has the same skeleton. <!doctype html> is line one — it tells the browser to use modern standards. <html lang=\"en\"> wraps everything and declares the language (helps screen readers and translation). Inside: <head> for the invisible metadata, <body> for everything visible. Learn this skeleton cold; every page you'll ever write starts here.",
      def: "The document skeleton: <!doctype html> declaration, one <html> root with a lang attribute, a <head> for metadata, and a <body> for visible content.",
      code: "<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\"\n          content=\"width=device-width,\n                  initial-scale=1\">\n    <title>My page</title>\n  </head>\n  <body>\n    <h1>Hello</h1>\n  </body>\n</html>\n\nThe minimum page that works.",
      out: { web: { h: "<h1>The skeleton, in action</h1><p>This page has a doctype, one html root with lang, a head with charset + viewport + title, and a body with visible content.</p>", c: "body{font-family:Georgia,serif;padding:24px;background:#faf7f0;color:#222} h1{border-bottom:3px solid #f5b23d;padding-bottom:8px}", j: "" } },
      flow: ["<!doctype html>", "<html lang>", "<head> (hidden)", "<body> (visible)"],
      task: "Write the full skeleton from memory (no looking), then compare. Add a <p> to the body. What shows in the browser tab, and why?",
      mistake: "Forgetting the doctype (the browser falls back to quirks mode and layouts can break subtly) or the viewport meta (the page won't scale properly on phones). Both are one line — never skip them.",
      tip: "The <title> is the only text on the page that appears in the browser tab AND in search results — so it doubles as your page's name in Google. Write it like a person would: \"Contact — MeenLearn\", not \"Page 2\".",
      challenge: "What's wrong with each: (a) two <body> tags, (b) a <title> inside <body>, (c) the doctype on line 3 instead of line 1? What would a validator report for each?" },

    { t: "What goes in the <head> (and why it's invisible)",
      text: "The <head> is the page's behind-the-scenes section. The browser reads it but never displays it on screen — it's for the browser and for machines, not for eyes. The essentials: <meta charset=\"UTF-8\"> (text encoding — must be near the top or emojis and accents break), <meta name=\"viewport\"> (makes the page scale on phones), <title> (the tab and search label), links to stylesheets and fonts, and icons. Everything a person can see belongs in <body> instead.",
      def: "The <head> holds metadata about the page — encoding, viewport, title, styles, icons — consumed by the browser and search engines but never rendered visibly.",
      code: "<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\"\n        content=\"width=device-width,\n                initial-scale=1\">\n  <meta name=\"description\"\n        content=\"One line for Google.\">\n  <title>Tab title</title>\n  <link rel=\"stylesheet\"\n        href=\"style.css\">\n</head>\n\nNothing here shows on screen.\nIt tells the browser how\nto treat the page.",
      out: { web: { h: "<p>This paragraph is in the <b>body</b> — visible.</p><p style=\"opacity:.6\">The head above this page holds: charset, viewport, description, title, and this stylesheet. None of it is painted on screen.</p>", c: "body{font-family:Georgia,serif;padding:24px;background:#14171f;color:#eceae3} p{background:#1c212c;padding:12px;border-radius:8px;border-left:3px solid #f5b23d} b{color:#f5b23d}", j: "" } },
      flow: ["charset (encoding)", "viewport (mobile)", "title (tab)", "links (styles/fonts)", "icons"],
      task: "Add a <meta name=\"description\"> to your page. Right-click the page in Chrome → \"View page source\" and confirm it's in the head. (You won't see it rendered anywhere — that's the point.)",
      mistake: "Putting visible content in the <head> (it disappears — the browser silently drops it from rendering) or putting <link rel=\"stylesheet\"> in the <body> (styles apply late, causing a flash of unstyled text). Head for metadata, body for content — no exceptions.",
      tip: "The charset meta must appear within the first 1,020 bytes of the file or browsers may ignore it. In practice: put it as the first thing inside <head>, right after the doctype.",
      challenge: "A page shows a broken emoji and a garbled accent (ï¿½). The developer says \"I only added text\". Name the two head elements that are probably missing or misplaced." },

    { t: "Headings and paragraphs: text with structure",
      text: "Text on a page isn't just text — it's structured. Headings (<h1> to <h6>, h1 biggest) mark the outline; paragraphs (<p>) are blocks of running text. Each page should have exactly one <h1> — the main title — with <h2> for sections and <h3> for subsections, in order. Don't pick a heading by its size (CSS handles that); pick it by its meaning in the outline.",
      def: "Headings (h1-h6) define a page's outline hierarchy; paragraphs (p) contain blocks of text. One h1 per page, nested levels in order.",
      code: "<h1>The full page title</h1>\n\n<h2>First section</h2>\n<p>Text for the section. A paragraph\nis a block: it starts on its own line\nand wraps at the container's width.</p>\n\n<h3>A subsection</h3>\n<p>Smaller heading, deeper level.</p>\n\nOne h1. h2 for sections.\nh3 for subsections. In order.",
      out: { web: { h: "<h1>One h1: the page title</h1><h2>Section one</h2><p>A paragraph is a block of text — it starts on its own line and wraps.</p><h3>Subsection</h3><p>Headings mark the outline, not just the size.</p>", c: "body{font-family:Georgia,serif;padding:24px;background:#faf7f0;color:#222;max-width:520px} h1{color:#b3543c} h2{color:#3a5fa0;border-bottom:2px solid #e2664f55} h3{color:#555} p{line-height:1.6}", j: "" } },
      flow: ["h1 (one)", "h2 (sections)", "h3 (subsections)", "p (text blocks)"],
      task: "Outline your favorite website's headings (view source, list every h1-h3). Is there exactly one h1? Are the levels in order? What's broken, if anything?",
      mistake: "Using <h1> for a big subtitle or <h3> after an <h1> (skipping levels). Screen readers navigate by heading order — a jumpy outline is a jumpy page. Size is a style decision; level is a meaning decision.",
      tip: "If you need a big subtitle, style a <p> or <div> larger with CSS — don't promote it to an <h1>. Keep the heading ladder honest: h1 → h2 → h3, never skip rungs.",
      challenge: "You're given a page with <h1>, then <h4>, then <h2>. List the accessibility and SEO problems, and rewrite the three tags correctly." },

    { t: "Links: connecting pages",
      text: "Links are the \"hyper\" in HTML: <a href=\"...\">text</a>. The href is the destination — another page (about.html), a section of this page (#contact), or a full URL. You can chain pages together, or link to a spot on the same page by giving the target an id and linking to #that-id. Add target=\"_blank\" (plus rel=\"noopener\") to open in a new tab.",
      def: "The <a> (anchor) element creates a hyperlink; its href attribute points to the destination — a page, a URL, or a fragment on the current page.",
      code: "<!-- to another page -->\n<a href=\"about.html\">About</a>\n\n<!-- to a section below -->\n<a href=\"#contact\">Contact us</a>\n...\n<h2 id=\"contact\">Contact</h2>\n\n<!-- to the internet -->\n<a href=\"https://developer.mozilla.org\"\n   target=\"_blank\" rel=\"noopener\">\n  MDN (new tab)\n</a>",
      out: { web: { h: "<p><a href=\"#bottom\" style=\"color:#5E8CE6;font-weight:bold\">Jump to the bottom</a> of this card.</p><p style=\"margin-top:14px\"><a href='index.html' target='_blank' rel='noopener' style=\"color:#5E8CE6;font-weight:bold\">Go to MeenLearn home (new tab)</a></p><p id=\"bottom\" style=\"margin-top:14px;color:#888;font-size:12px\">You made it to the bottom via #bottom.</p>", c: "body{font-family:sans-serif;padding:24px;background:#fff;color:#222}", j: "" } },
      flow: ["<a> wraps text", "href = destination", "page / #section / URL", "click -> navigate"],
      task: "Build a page with three sections and a small nav at the top that links to each via #id. Test that clicking each link jumps (and scrolls) to the section.",
      mistake: "Forgetting rel=\"noopener\" on target=\"_blank\" links — it's a security fix that prevents the opened page from manipulating your window. And: an href=\"#\" with no target scrolls to top and does nothing useful; use a real target or a button.",
      tip: "The link text should say where it goes: \"Read the CSS guide\" beats \"click here\" — especially for screen-reader users who browse links as a flat list.",
      challenge: "Create a page where a link scrolls to a section 3 screens down, and a second link goes back up to the top. Which element needs the id, and what does the top link point to?" },

    { t: "Images: src, alt, and why they matter",
      text: "Images: <img src=\"cat.jpg\" alt=\"A sleeping cat\">. src is the file location (relative like cat.jpg or absolute like https://...). alt is the text shown if the image fails to load AND what screen readers announce — always write meaningful alt text. Images are inline elements (they flow within text), so you'll usually need CSS to control their size. Keep files small: JPEG/WEBP for photos, SVG for icons and logos.",
      def: "The <img> element embeds an image: src points to the file, alt provides an accessible text alternative. It's a void element (no closing tag).",
      code: "<img src=\"cat.jpg\"\n     alt=\"A sleeping cat\"\n     width=\"300\">\n\nsrc: where the file is\nalt: what it shows/says if it\n    can't load (and for screen\n    readers, always)\n\nVoid element: no </img>.\n\nDecorative image? alt=\"\"\n(alt present but empty).",
      out: { web: { h: "<img src=\"https://picsum.photos/seed/meen/300/180\" alt=\"A placeholder photo\" style=\"border-radius:10px;display:block;margin-bottom:10px\"><p style=\"font-size:12px;color:#666\">If that image failed to load, you'd see: <b>\"A placeholder photo\"</b> — that's the alt text doing its job.</p>", c: "body{font-family:sans-serif;padding:24px;background:#faf7f0;color:#222}", j: "" } },
      flow: ["<img src>", "file loads", "fails? show alt", "screen reader reads alt"],
      task: "Add two images to a page: one meaningful (with descriptive alt) and one decorative (empty alt). Break the first src on purpose — what appears in its place?",
      mistake: "Writing alt=\"cat.jpg\" or alt=\"image1\" — that's the filename, not a description. Alt should describe the content or purpose: \"Graph of monthly sales, rising in Q2\". And never omit alt entirely — validators flag it, screen readers read the filename instead.",
      tip: "Modern practice: add loading=\"lazy\" to images below the fold so the page loads fast (the browser fetches them as you scroll). And always set a width (or CSS max-width: 100%) so huge images don't blow out the layout while loading.",
      challenge: "A photo of a company logo: should its alt say the company name or be empty? A chart showing quarterly revenue: what should its alt say? Argue both." },

    { t: "Lists: bullets, numbers, and nesting",
      text: "Two list types: <ul> for unordered (bulleted) lists where order doesn't matter, and <ol> for ordered (numbered) lists where it does (recipes, rankings). Each item is an <li>. You can nest a list inside an <li> for sub-items. The browser numbers <ol> automatically — you never type the numbers yourself.",
      def: "<ul> (unordered) and <ol> (ordered) contain <li> items; order matters for <ol> (auto-numbered) and not for <ul> (bulleted).",
      code: "<ul>\n  <li>HTML</li>\n  <li>CSS\n    <ul>\n      <li>Flexbox</li>\n      <li>Grid</li>\n    </ul>\n  </li>\n</ul>\n\n<ol>\n  <li>Boil water</li>\n  <li>Add coffee</li>\n  <li>Pour</li>\n</ol>\n\nBullets vs auto-numbers.\nNest <ul>/<ol> inside <li>.",
      out: { web: { h: "<p><b>Skills (unordered):</b></p><ul><li>HTML</li><li>CSS<ul><li>Flexbox</li><li>Grid</li></ul></li></ul><p><b>Making coffee (ordered):</b></p><ol><li>Boil water</li><li>Add coffee</li><li>Pour slowly</li></ol>", c: "body{font-family:Georgia,serif;padding:24px;background:#fff;color:#222;max-width:420px} ul{background:#f4f2ea;padding:12px 12px 12px 28px;border-radius:8px} ol{background:#eef3fb;padding:12px 12px 12px 28px;border-radius:8px} b{color:#b3543c}", j: "" } },
      flow: ["<ul> or <ol>", "items as <li>", "nest for sub-items", "browser formats them"],
      task: "Build a recipe as an <ol> (at least 4 steps, one with a nested <ul> of ingredients). Then build your tech stack as a <ul>. Which one would break if you rearranged the items, and why?",
      mistake: "Using <ol> for a list where order doesn't matter (a shopping list gets numbered, which is wrong), or putting text directly in <ul> without wrapping it in <li> (the browser tolerates it, but it's invalid and validators flag it).",
      tip: "The browser does the formatting — don't type \"1. 2. 3.\" into an ordered list or bullet characters into an unordered one. If you need custom markers, that's a CSS job (list-style).",
      challenge: "Why can't you put an <ol> directly inside a <p>? (Hint: some elements can't contain block-level content.) What's the right structure for \"a paragraph followed by a numbered list\"?" },

    { t: "Tables: real tabular data",
      text: "Tables are for data that is genuinely two-dimensional — rows of records with columns of fields (a price list, a schedule, results). Structure: <table> → rows are <tr> → cells are <th> (header) or <td> (data). Wrap headers in <thead> and data in <tbody>. The big rule: never use tables to lay out a page (that's CSS grid/flexbox) — tables are for data only.",
      def: "<table> structures two-dimensional data: <tr> rows containing <th> header cells and <td> data cells, grouped in <thead>/<tbody>.",
      code: "<table>\n  <thead>\n    <tr>\n      <th>Item</th><th>Price</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>Tea</td><td>$2</td>\n    </tr>\n    <tr>\n      <td>Coffee</td><td>$4</td>\n    </tr>\n  </tbody>\n</table>\n\nData in. Layout out.",
      out: { web: { h: "<table><thead><tr><th>Track</th><th>Lessons</th><th>Level</th></tr></thead><tbody><tr><td>HTML</td><td>20</td><td>Beginner</td></tr><tr><td>CSS</td><td>20</td><td>Beginner</td></tr><tr><td>JavaScript</td><td>20</td><td>Core</td></tr></tbody></table>", c: "body{font-family:sans-serif;padding:24px;background:#fff;color:#222} table{border-collapse:collapse;width:100%;max-width:420px} th,td{padding:10px 14px;border:1px solid #ddd;text-align:left} th{background:#14171f;color:#f5b23d} tbody tr:nth-child(even){background:#f7f5ef}", j: "" } },
      flow: ["<table>", "<thead> headers", "<tbody> rows of <tr>", "<th>/<td> cells"],
      task: "Build a table of your 5 favorite movies: title, year, rating. Add a <thead> with a header row. Then style it (borders, header background) with a few CSS rules.",
      mistake: "Using tables to build page layouts (a 2-column \"table\" for header + sidebar). It works in 1999 and it's the wrong tool today — no responsive behavior, no accessibility, and CSS grid does it better. If you're reaching for a table to arrange boxes, stop and use CSS.",
      tip: "Always include the header row in <thead> — screen readers announce it for every row, and you can style it (repeating headers, sticky headers) without extra hacks.",
      challenge: "A \"table\" has a row of 3 cells, but the first cell in the data row contains both a name and an email. What's the design problem (hint: one column, one kind of value), and how do you fix the columns?" },

    { t: "Forms and inputs: collecting data",
      text: "Forms collect user input: a <form> wraps fields, and a submit button sends them somewhere. Each field is an <input> with a type (text, email, password, number, checkbox, date, ...) and — crucially — a <label> tied to it. The form's action attribute names the destination, and method (GET/POST) controls how the data travels. Without labels, your form is unusable for keyboard and screen-reader users.",
      def: "A <form> collects input via typed <input> fields (and other controls), submits to an action URL using a method, and must pair every field with a <label>.",
      code: "<form action=\"/signup\" method=\"post\">\n  <label for=\"email\">Email</label>\n  <input id=\"email\" name=\"email\"\n         type=\"email\" required>\n\n  <label for=\"pw\">Password</label>\n  <input id=\"pw\" name=\"password\"\n         type=\"password\">\n\n  <button type=\"submit\">Sign up</button>\n</form>\n\nlabel for=\"id\" <-> input id.\nname = the key the server sees.",
      out: { web: { h: "<form id=\"f\"><label for=\"n\" style=\"display:block;margin-bottom:4px\">Your name</label><input id=\"n\" name=\"n\" type=\"text\" placeholder=\"Ada\" style=\"padding:8px;width:100%;margin-bottom:12px;border:1px solid #ccc;border-radius:6px\"><label for=\"e\" style=\"display:block;margin-bottom:4px\">Email</label><input id=\"e\" name=\"e\" type=\"email\" placeholder=\"ada@x.com\" style=\"padding:8px;width:100%;margin-bottom:12px;border:1px solid #ccc;border-radius:6px\"><button type=\"submit\" style=\"padding:8px 16px;background:#f5b23d;border:0;border-radius:6px;font-weight:bold\">Submit</button></form><p id=\"out\" style=\"margin-top:10px;color:#2c8a63;font-weight:bold\"></p>", c: "body{font-family:sans-serif;padding:24px;background:#faf7f0;color:#222;max-width:340px}", j: "document.getElementById('f').addEventListener('submit', function(e){ e.preventDefault(); var n=document.getElementById('n').value; document.getElementById('out').textContent = n ? 'Got it, '+n+'!' : 'Name is required.'; });" } },
      flow: ["<form> wraps fields", "<input type> per field", "<label for> ties in", "submit -> action"],
      task: "Build a login form: email + password + submit. Give every input an id and a matching <label for>. Tab through it with your keyboard — clicking a label should focus its input.",
      mistake: "Inputs without labels (or labels not tied with for/id) — the #1 accessibility failure on forms. Also: using type=\"text\" for an email (you lose keyboard hints, validation, and the @-check for free) or forgetting name=\"...\" (the server receives nothing).",
      tip: "Input types give you behavior for free: type=\"email\" validates the format, type=\"password\" masks the text, type=\"number\" shows arrow keys, type=\"date\" opens a date picker. Use the right type and CSS/JS do less work.",
      challenge: "A form submits to /signup but the server gets an empty email field. The input has id=\"email\" but no name attribute. What's happening, and what's the one-line fix? (Why does id work for the label but not for the server?)" },

    { t: "Buttons, labels, and making forms usable",
      text: "Buttons come in two flavors: <button> (a plain button you wire up with JavaScript) and <input type=\"submit\"> (submits its form automatically). Inside a form, the submit button is the default. And the label rule from the last lesson, in full: every input gets a <label for=\"id\"> pointing at the input's id — it enlarges the click target, guides screen readers, and is non-negotiable for accessible forms.",
      def: "<button> is a generic clickable control; <input type=\"submit\"> submits its parent form. Every form control should have an associated <label> via for/id.",
      code: "<button>Save draft</button>\n\n<input type=\"submit\" value=\"Send\">\n\n<button type=\"submit\">Send</button>\n\n<button> (default type is button:\nno submit). <input type=\"submit\">\nsubmits its form automatically.\n\nLabel the rest:\n<label for=\"search\">Search</label>\n<input id=\"search\" type=\"search\">",
      out: { web: { h: "<div style=\"display:flex;gap:10px;flex-wrap:wrap\"><button id=\"b1\" style=\"padding:10px 16px;border:1px solid #ccc;border-radius:8px;background:#fff;cursor:pointer\">Plain button</button><form style=\"display:flex\"><input id=\"q\" type=\"text\" placeholder=\"type here\" style=\"padding:10px;border:1px solid #ccc;border-radius:8px 0 0 8px;margin:0\"><button type=\"submit\" style=\"padding:10px 16px;border:0;border-radius:0 8px 8px 0;background:#f5b23d;font-weight:bold;cursor:pointer\">Submit</button></form></div><p id=\"msg\" style=\"margin-top:12px;color:#555\"></p>", c: "body{font-family:sans-serif;padding:24px;background:#fff;color:#222}", j: "document.getElementById('b1').addEventListener('click',function(){document.getElementById('msg').textContent='Plain button clicked — nothing submitted.'}); document.querySelector('form').addEventListener('submit',function(e){e.preventDefault();document.getElementById('msg').textContent='Form submitted with: '+document.getElementById('q').value});" } },
      flow: ["<button> = generic", "<input type=submit> = submits", "label for = id", "both are keyboard-accessible"],
      task: "Build a search bar: an <input type=\"search\"> with a label and a submit button. On submit (prevent the reload with JS for now), show what the user typed. Test it with the keyboard only.",
      mistake: "Using a <div> or <span> styled to look like a button — it's invisible to keyboard and screen-reader users. Use real <button> or <a> elements and style them; semantics first, pixels second.",
      tip: "A label click focuses its input for free — test by clicking the word next to a field. If it doesn't focus, your for/id pairing is broken (typos are the usual cause).",
      challenge: "Why does <button> inside a form submit the form by default in some browsers but a plain <button> outside a form does nothing? (Answer: button's default type, and whether a form wraps it.) What type attribute makes a button inside a form NOT submit?" },

    { t: "Semantic structure: main, nav, section, article, footer",
      text: "Semantic tags name what a region IS: <header> (top of page), <nav> (primary links), <main> (the one main content area), <article> (self-contained content like a post), <section> (a themed group), <aside> (side info), <footer> (bottom). Instead of <div class=\"nav\">, just use <nav>. Screen readers can jump between landmarks, search engines understand the structure, and other developers read your page like a book.",
      def: "Semantic elements (header, nav, main, article, section, aside, footer) describe a region's meaning, enabling accessibility landmarks, better SEO, and readable markup.",
      code: "<header>  <h1>Site title</h1> <nav>...</nav> </header>\n<main>\n  <article>\n    <h2>Post title</h2>\n    <p>Self-contained content...</p>\n  </article>\n  <aside>Related links</aside>\n</main>\n<footer>Copyright, small links</footer>\n\nOne <main> per page.\nMeaning, not just boxes.",
      out: { web: { h: "<header style=\"background:#14171f;color:#fff;padding:12px 16px;border-radius:8px 8px 0 0\"><b>MeenLearn</b> <span style=\"float:right;font-size:12px\">nav goes here</span></header><main style=\"padding:16px\"><article><h3 style=\"margin:0 0 6px\">An article: self-contained</h3><p style=\"margin:0;color:#555\">This content could stand alone on its own page.</p></article></main><aside style=\"padding:12px 16px;background:#f4f2ea;font-size:12px;color:#777\">Aside: side information</aside><footer style=\"padding:12px 16px;background:#eee;font-size:11px;color:#888;border-radius:0 0 8px 8px\">Footer: bottom of page</footer>", c: "body{font-family:sans-serif;padding:24px;background:#fff;color:#222;max-width:440px}", j: "" } },
      flow: ["<header>", "<nav>", "<main> (one!)", "<article>/<section>", "<aside>", "<footer>"],
      task: "Rebuild a simple page (like this lesson's example) using only semantic tags — no <div> for layout. Then open a real site's source and count its <div class=\"...\">s vs its semantic tags.",
      mistake: "Using <div> for everything (the page is a wall of boxes with no meaning), or multiple <main>/<h1> per page (breaks the \"one main area\" contract screen readers rely on). If a region has a name, use the tag with that name.",
      tip: "Quick decision tree: is it the top of the page? <header>. A list of primary links? <nav>. The core content? <main>. A standalone piece (a post, a card)? <article>. A themed group? <section>. Side info? <aside>. Bottom? <footer>. If none fit, <div> is fine.",
      challenge: "A blog page has: logo, nav, a list of posts, a sidebar with ads, and copyright. Assign a semantic tag to each region. Which region could be BOTH an <aside> and an <article> — and which should it be?" },

    { t: "Attributes: the name=\"value\" extras",
      text: "Attributes add information to an element: <a href=\"...\">, <img src alt>, <div class=\"card\" id=\"top\">. Always name=\"value\" with the value in quotes. The ones you'll use daily: href (link destination), src (file source), alt (image text), class (a styling hook — repeatable), and id (a unique identifier — once per page). class is for groups and CSS; id is for one-of-a-kind targets and JS.",
      def: "Attributes are name=\"value\" pairs on an element that provide extra data: destinations (href), sources (src), descriptions (alt), hooks (class, id).",
      code: "<a href=\"about.html\">link</a>\n<img src=\"cat.jpg\" alt=\"A cat\">\n<div class=\"card highlight\">...\n\nAttribute rules:\n  - name=\"value\" (quotes!)\n  - class: repeatable, for CSS groups\n  - id: unique per page, for targets/JS\n  - some are boolean: <input disabled>\n\nAn element = tag + attributes\n+ content, all nested properly.",
      out: { web: { h: "<p><span class=\"tag\" style=\"background:#e2664f22;color:#b3543c;padding:2px 8px;border-radius:4px;font-family:monospace;font-size:12px\">href</span> = where a link goes</p><p><span class=\"tag\" style=\"background:#5E8CE622;color:#3a5fa0;padding:2px 8px;border-radius:4px;font-family:monospace;font-size:12px\">src / alt</span> = image file + its text</p><p><span class=\"tag\" style=\"background:#f5b23d22;color:#9a7020;padding:2px 8px;border-radius:4px;font-family:monospace;font-size:12px\">class</span> = a repeatable styling hook</p><p><span class=\"tag\" style=\"background:#55A87322;color:#2c6e49;padding:2px 8px;border-radius:4px;font-family:monospace;font-size:12px\">id</span> = a unique target (one per page)</p>", c: "body{font-family:sans-serif;padding:24px;background:#faf7f0;color:#222;max-width:420px} p{margin:8px 0}", j: "" } },
      flow: ["tag opens", "attributes on the tag", "content inside", "tag closes"],
      task: "Build a card with an <img> (with alt), an <h3>, a <p>, and two <a> links. Give the card class=\"card\" and id=\"top-card\". What's the difference between using class and id here?",
      mistake: "Unquoted attribute values (href=about.html — works sometimes, breaks with spaces or special characters) and duplicate ids on one page (validators flag it; :target and getElementById get confused). Quotes always, ids once.",
      tip: "class vs id, the one-line version: use class when more than one element might share the styling (buttons, cards); use id when exactly one element exists and needs a unique anchor (a form target, a scroll destination).",
      challenge: "You need three cards that look identical but one is also a scroll target. Which attribute carries the shared styling, which carries the unique target, and can an element have both? (Yes — show it.)" },

    { t: "Block vs inline: how elements flow",
      text: "Every element has a default display behavior. Block elements (div, p, h1, ul, form) start on a new line and stretch to full width. Inline elements (span, a, strong, em, img) flow within the text and can't have width/height. This default is why a paragraph breaks but a link doesn't — and CSS's display property can override it when you need to.",
      def: "Block elements occupy their own line and full width (p, div, h1); inline elements flow within text (span, a, strong). CSS display can override the default.",
      code: "BLOCK (own line, full width):\n  p, div, h1, ul, form, table\n\nINLINE (flows in text):\n  span, a, strong, em, img\n\n<p>This has <strong>bold</strong>\nand a <span>marked</span> word.\nThey stay in the sentence.</p>\n\n<p>But this paragraph starts\non a new line — it's block.</p>",
      out: { web: { h: "<p>This paragraph is <strong>block</strong>: it starts on its own line.</p><p>Inside it, these are <span style=\"background:#f5b23d;padding:1px 4px;border-radius:3px\">inline</span> — they flow with the text: <a href=\"#\" style=\"color:#5E8CE6\">a link</a> and <em>emphasis</em>.</p><div style=\"background:#14171f;color:#f5b23d;padding:8px 12px;border-radius:6px;font-family:monospace;font-size:12px\">div is block too — note its own line.</div>", c: "body{font-family:Georgia,serif;padding:24px;background:#fff;color:#222;max-width:440px;line-height:1.6}", j: "" } },
      flow: ["Element has a type", "block: own line", "inline: in text", "CSS can override"],
      task: "Write a paragraph with a <span>, a <strong>, and an <a> inside it. Then add a <div> between two paragraphs. Predict (then verify) how each appears — which break the line, which don't?",
      mistake: "Trying to set width/height on an inline element (it's ignored — that's why your styled <span> won't stretch), or expecting a <div> to sit next to another <div> (they stack by default; put them in a flex container to place side by side).",
      tip: "When layout is \"wrong\", first ask: what's the default display of each element? Half of beginner layout confusion is forgetting that divs stack and spans flow — the rest is CSS doing exactly what you asked.",
      challenge: "Why can't you make an <a> a full-width button just by setting width:100%? (Answer: it's inline.) What's the one CSS property that fixes it, and what does it change the link into?" },

    { t: "Special characters and entities",
      text: "HTML reserves some characters for its own syntax, so you can't type them directly in content. The usual suspects: < and > (they'd be read as tags), & (it starts an entity), and quotes. The fix is entities: &lt; for <, &gt; for >, &amp; for &, &quot; for \". You'll see this whenever you want to display code as text instead of having the browser execute it.",
      def: "HTML entities are named or coded representations of reserved characters (&lt; &gt; &amp; &quot; &nbsp;) that let you display them as text.",
      code: "Want to SHOW:   <p>Hi</p>\nWrite:            &lt;p&gt;Hi&lt;/p&gt;\n\nWant: 3 < 5 and 5 > 3\nWrite: 3 &lt; 5 and 5 &gt; 3\n\nWant: Sam & Ada\nWrite: Sam &amp; Ada\n\n&nbsp; = a space that can't\nwrap (no line break there).",
      out: { web: { h: "<p style=\"font-family:monospace;background:#14171f;color:#9fe8d8;padding:12px;border-radius:8px;font-size:13px\">&lt;p&gt;This text is <em>displayed</em>, not executed.&lt;/p&gt;</p><p style=\"margin-top:10px\">The line above uses &lt; &gt; entities. 3 &lt; 5 is true, and Sam &amp; Ada are friends.</p>", c: "body{font-family:sans-serif;padding:24px;background:#faf7f0;color:#222;max-width:440px}", j: "" } },
      flow: ["Reserved char in content?", "Yes? use entity", "&lt; &gt; &amp;", "Browser shows the char"],
      task: "Write an HTML page that displays the text: <div class=\"box\"> & <span> — exactly, as visible text (not as executed HTML). How many entities did you need?",
      mistake: "Typing a raw < in text and having the browser treat it as a tag start (the rest of your page can go wrong in unpredictable ways). And using & for \"and\" in prose — it usually renders, but it's technically invalid and a validator will flag it.",
      tip: "When in doubt, &amp; is safe: it's the entity for & itself, so &amp;lt; displays &lt;. Nested escaping is how you display code that displays code — a rare but real need.",
      challenge: "Why does &nbsp; exist when a normal space works? (Hint: line wrapping.) Where would you specifically use it — think about a date like 30/08/2026 that you don't want the browser to break across two lines?" },

    { t: "Media: video and audio",
      text: "HTML has built-in media: <video src=\"clip.mp4\" controls></video> and <audio src=\"song.mp3\" controls></audio>. The controls attribute adds the play/pause/seek UI. For multiple formats or a poster image, nest <source> elements inside. For YouTube and similar, an <iframe> embed is the standard — you can't host third-party video in a plain <video>.",
      def: "<video> and <audio> embed media with a controls attribute; <source> child elements offer multiple formats; iframes embed external players.",
      code: "<video controls width=\"320\">\n  <source src=\"clip.webm\">\n  <source src=\"clip.mp4\">\n  Your browser can't play video.\n</video>\n\n<audio controls src=\"song.mp3\">\n</audio>\n\ncontrols = play/pause/seek UI.\n<video> closes (it has content);\n<audio> is self-closing-ish here.\n\nYouTube? <iframe> embed, not <video>.",
      out: { web: { h: "<div style=\"background:#14171f;border-radius:10px;padding:16px;color:#fff;font-family:monospace;font-size:12px\"><p style=\"margin:0 0 8px;color:#9fe8d8\">video / audio tags</p><p style=\"margin:0;font-size:11px;color:#aaa\">controls adds the UI. Multiple &lt;source&gt; = format fallback. YouTube uses an iframe instead.</p></div><p style=\"font-size:12px;color:#777;margin-top:10px\">No media file here (to keep the example light) — but the structure above is what your page would use.</p>", c: "body{font-family:sans-serif;padding:24px;background:#faf7f0;color:#222;max-width:440px}", j: "" } },
      flow: ["<video>/<audio>", "src or <source> children", "controls for UI", "fallback text inside"],
      task: "Add a <video> element with controls to a page (use any small sample video URL you find, or just the structure with no src). What does the browser show before the video loads, and how do you add a poster image?",
      mistake: "Forgetting controls (you get a video with no way to play it) or pointing <video> at a YouTube URL (it won't work — YouTube requires the iframe embed). Also: always include fallback text inside <video> for ancient browsers.",
      tip: "Offer two formats via <source> (webm + mp4) to cover more browsers, and keep media files small — a 10MB hero video will kill your load time on mobile. Compress, or use a short loop with no sound.",
      challenge: "Why can't <audio> have a poster or width, and why is that fine? (Hint: what does audio actually display?) What element WOULD you style for a custom audio player's look?" },

    { t: "Embedding: iframes and when to use them",
      text: "An <iframe> embeds another web page inside your page: <iframe src=\"...\" title=\"...\"></iframe>. It's the standard for YouTube, maps, and third-party widgets. Always give it a title (accessibility) and explicit dimensions. Note that the embedded page runs in its own context — sandboxing attributes control how much it can do. Use iframes for external content, not as a layout tool.",
      def: "The <iframe> element embeds another document inside the current page, used for maps, video players, and third-party widgets; always include a title.",
      code: "<iframe\n  src=\"https://www.openstreetmap.org/export/embed.html?...\"\n  width=\"400\" height=\"250\"\n  title=\"Map of Lagos\">\n</iframe>\n\n  src: the page to embed\n  title: what it is (screen readers)\n  width/height: size it explicitly\n\nAlso: <iframe> for YouTube embeds.\nNOT for laying out your own page.\nYour own page = your own HTML.",
      out: { web: { h: "<div style=\"border:2px dashed #ccc;border-radius:8px;padding:14px;text-align:center;background:#f7f5ef\"><p style=\"margin:0;font-size:12px;color:#888;font-family:monospace\">an iframe would live here:<br>(a map, a YouTube player, a widget)</p></div><p style=\"font-size:12px;color:#666;margin-top:10px\">Structure: src = embedded page, title = its description, explicit width/height. Own layout? Use your own HTML + CSS, not an iframe.</p>", c: "body{font-family:sans-serif;padding:24px;background:#fff;color:#222;max-width:440px}", j: "" } },
      flow: ["<iframe src>", "browser loads that page inside", "title describes it", "sandbox limits its powers"],
      task: "Add an OpenStreetMap embed iframe to a page (the openstreetmap.org export page gives you the iframe snippet). Give it a title and dimensions. What breaks if you remove the title?",
      mistake: "Using iframes to build your own page layout (a frame for the header, one for the sidebar) — that's the 1998 way and it's terrible: no shared styling, no responsive flow, accessibility nightmares. Iframes are for external content only.",
      tip: "Embedding untrusted content? Add the sandbox attribute (with specific allowances) so the embedded page can't read your cookies or pop windows. For YouTube, use the official embed URL — it's designed for exactly this.",
      challenge: "You embed a page with src=\"https://example.com\". The developer says it \"works on my machine\" but shows blank for users. Name two likely causes (hint: one is about the server's headers, one is about your dimensions)." },

    { t: "Metadata that works: SEO, Open Graph, and why it matters",
      text: "The <head> has metadata that shapes how your page is found and shared. The essentials: <meta charset>, <meta name=\"viewport\"> (mobile), <title> (tab + search), and <meta name=\"description\"> (the line under your title in search results). Open Graph tags (og:title, og:description, og:image) control the rich preview when someone shares your link on social media. None of this is visible on the page — all of it is visible in search and on feeds.",
      def: "SEO metadata (title, description, viewport) shapes search visibility; Open Graph tags shape how links appear when shared on social platforms.",
      code: "<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\"\n        content=\"width=device-width,\n                initial-scale=1\">\n  <title>Learn CSS — MeenLearn</title>\n  <meta name=\"description\"\n        content=\"20 clear CSS lessons:\n        box model, flexbox, grid,\">\n\n  <!-- Open Graph (sharing) -->\n  <meta property=\"og:title\"\n        content=\"Learn CSS — MeenLearn\">\n  <meta property=\"og:description\"\n        content=\"...\">\n  <meta property=\"og:image\"\n        content=\"https://.../cover.jpg\">\n</head>",
      out: { web: { h: "<div style=\"border:1px solid #ddd;border-radius:10px;padding:14px;background:#f9fafb;max-width:360px\"><div style=\"font-size:10px;color:#888\">search result preview</div><div style=\"font-size:11px;color:#1a73e8;margin:4px 0\">meenlearn.com/css</div><div style=\"font-size:14px;color:#1a0dab;font-weight:600\">Learn CSS — MeenLearn</div><div style=\"font-size:12px;color:#545454\">20 clear CSS lessons: box model, flexbox, grid, responsive design and animation.</div></div>", c: "body{font-family:sans-serif;padding:24px;background:#fff;color:#222}", j: "" } },
      flow: ["title (tab + search)", "description (search line)", "viewport (mobile)", "og:* (social preview)"],
      task: "Write a <title> and <meta description> for your own project (one line each). Then draft the three Open Graph tags for it. Paste the description into a Google search bar — does it read like something you'd click?",
      mistake: "A <title> that's just the site name on every page (search engines can't tell pages apart) or a description that's keyword spam. Write like a human: specific, one sentence, worth clicking.",
      tip: "The og:image is the most-ignored and most-visible tag: it's the thumbnail on every shared link. Make it a wide, branded image (1200×630 is the standard) and it does quiet marketing for you on every share.",
      challenge: "Your page's link, when shared, shows a generic site title and a blank image. The developer says \"the og tags are in the head\". List three things to check (hint: one is about the image URL, one about the tag name, one about caching)." },

    { t: "Accessibility: alt, labels, and the keyboard test",
      text: "Accessible HTML helps everyone: screen-reader users, keyboard-only users, people on slow connections. The non-negotiables: meaningful alt text on images, labels on every form input, one <h1> per page with a sensible heading order, semantic landmarks (nav, main, footer), and links/buttons that are real elements. The fastest audit: tab through your page with only the keyboard. If you can't use it, a keyboard user can't either.",
      def: "Accessible HTML uses meaningful alt text, labeled controls, one h1 with ordered headings, semantic landmarks, and real interactive elements — verified by a keyboard-only pass.",
      code: "DO:                                  DON'T:\n<img alt=\"Chart of sales, up 20%\">   <img alt=\"image1\">\n<label for=\"e\">Email</label>          <input> (no label)\n<h1>Title</h1><h2>Section</h2>         <h1>, then <h4>\n<nav>...</nav>                        <div class=\"nav\">...\n<button>Save</button>                 <div>Save</div>\n\nAudit: TAB through the page.\nCan you do everything with the\nkeyboard? If not, fix it.",
      out: { web: { h: "<h3 style=\"margin-top:0\">Keyboard test, live</h3><p style=\"font-size:13px;color:#555\">Press <b>TAB</b> now. Watch which elements get a focus ring in order: the image (skipped — decorative), then the link, then the button. That order IS the reading order for a screen reader.</p><a href=\"#\" style=\"color:#5E8CE6\">A real link</a><br><button onclick=\"this.textContent='Clicked! (a real button)';this.style.background='#55A873';this.style.color='#fff'\" style=\"padding:8px 14px;border:1px solid #ccc;border-radius:6px;cursor:pointer;margin-top:8px\">A real button</button>", c: "body{font-family:sans-serif;padding:24px;background:#faf7f0;color:#222;max-width:420px}", j: "" } },
      flow: ["alt on images", "labels on inputs", "one h1, ordered", "semantic landmarks", "real buttons/links"],
      task: "Take any form you've built and run the keyboard test: can you tab to every field, is the label announced (check the tab order), and can you submit without a mouse? Fix everything that fails.",
      mistake: "A <div> styled as a button (no keyboard access at all) or an image with alt=\"cool picture\" (meaningless). Screen readers don't see pixels — they read your markup. Markup that's vague to a machine is vague to a human with a screen reader.",
      tip: "Contrast matters: text on a background must be readable without color-vision assumptions. A quick check: if you desaturate your page (grayscale), can you still tell what's a link and what's body text?",
      challenge: "A page has <div class=\"button\">Buy now</div> with an onclick. It works with a mouse. What exactly breaks for a keyboard user and a screen-reader user, and what's the two-word fix (the element you should use instead)?" },

    { t: "Validation and how to check your HTML",
      text: "Two tools keep your HTML honest. The W3C validator (validator.w3.org) — paste your HTML or give it a URL and it reports every error and warning with line numbers. And your browser's DevTools (right-click → Inspect) shows the page as the browser actually parsed it, including how it recovered from your mistakes. Fix errors in the order reported: unclosed tags, missing attributes, and duplicate ids are the usual suspects.",
      def: "HTML validation means checking markup against the spec — via the W3C validator (errors + warnings) and DevTools (the parsed DOM as the browser built it).",
      code: "W3C validator: validator.w3.org\n  -> paste HTML or enter URL\n  -> list of errors with line #\n\nDevTools: right-click -> Inspect\n  -> Elements tab = the real DOM\n  -> shows how the browser\n     recovered from your bugs\n\nFix top-down:\n  - unclosed tags\n  - missing required attributes\n  - duplicate ids\n  - content in the wrong parent",
      out: { web: { h: "<div style=\"font-family:monospace;font-size:12px;background:#14171f;color:#e2664f;padding:12px;border-radius:8px\"><span style=\"color:#888\">Example validator error:</span><br>&lt;p&gt; missing end tag (line 14)</div><div style=\"font-family:monospace;font-size:12px;background:#14171f;color:#55A873;padding:12px;border-radius:8px;margin-top:8px\"><span style=\"color:#888\">After the fix:</span> No errors or warnings.</div><p style=\"font-size:12px;color:#666;margin-top:10px\">The browser is forgiving — it guesses when your markup is broken. The validator doesn't guess: it tells you exactly what's wrong.</p>", c: "body{font-family:sans-serif;padding:24px;background:#faf7f0;color:#222;max-width:440px}", j: "" } },
      flow: ["Write the HTML", "Validate (W3C)", "Fix errors top-down", "Inspect in DevTools"],
      task: "Deliberately introduce three mistakes into a page (an unclosed <p>, a duplicate id, an <img> without alt). Validate it, read all three reports, then fix them and re-validate until it's clean.",
      mistake: "Trusting the browser's rendering as proof of correctness — the browser silently repairs broken markup, so a page can look fine while being invalid (and break in another browser or for a screen reader). \"It looks right\" is not the same as \"it's right\".",
      tip: "Warnings (not errors) are worth fixing too: a <div> inside a <p>, or deprecated attributes. They're usually the early signs of structural problems that grow into real bugs.",
      challenge: "Your page validates clean, but a user reports the layout is broken in Safari. The validator was happy. What does this tell you about what validation checks (and what it can't check)?" },

    { t: "Project: build a complete personal page",
      opt: ["vscode"],
      text: "The capstone: a full personal page using everything from the track. The spec: a semantic skeleton (header with nav, main, footer), a heading structure (one h1, h2 sections), at least one image with real alt text, a list of skills, a table of projects, a contact form (with labeled inputs), and a full head (charset, viewport, title, description). Bonus: internal links (#sections) and one external link in a new tab. Validate it before calling it done.",
      def: "A personal page combining: semantic structure, correct heading order, images with alt, lists, a table, a labeled form, and a complete <head> — validated clean.",
      code: "SPEC (your checklist):\n[ ] <!doctype> + <html lang>\n[ ] <head>: charset, viewport,\n    title, description\n[ ] <header> with <nav>\n[ ] one <h1>, <h2> per section\n[ ] <main> wrapping content\n[ ] image with meaningful alt\n[ ] skills as <ul>\n[ ] projects as <table>\n[ ] contact form: labels + ids\n[ ] <footer>\n[ ] validated: 0 errors\n\nBuild it, then validate.\nThis is the HTML track, done.",
      out: { web: { h: "<header style=\"background:#14171f;color:#fff;padding:14px 18px\"><b style=\"color:#f5b23d\">Ada L.</b> <span style=\"float:right;font-size:12px\"><a href=\"#work\" style=\"color:#ccc\">Work</a> · <a href=\"#contact\" style=\"color:#ccc\">Contact</a></span></header><main style=\"padding:18px\"><h2 id=\"work\" style=\"color:#b3543c\">Work</h2><table style=\"border-collapse:collapse;width:100%;font-size:13px\"><tr style=\"background:#f4f2ea\"><th style=\"text-align:left;padding:6px\">Project</th><th style=\"text-align:left;padding:6px\">Stack</th></tr><tr><td style=\"padding:6px;border-top:1px solid #eee\">Portfolio</td><td style=\"padding:6px;border-top:1px solid #eee\">HTML/CSS</td></tr></table><h2 id=\"contact\" style=\"color:#b3543c;margin-top:18px\">Contact</h2><p style=\"font-size:13px\">Form with labeled inputs — the full page has charset, viewport, title, description.</p></main><footer style=\"padding:12px 18px;background:#f4f2ea;font-size:11px;color:#888\">Built with the HTML track.</footer>", c: "body{font-family:sans-serif;background:#faf7f0;color:#222;margin:0;max-width:520px}", j: "" } },
      flow: ["Checklist", "Build each section", "Label every input", "Validate clean", "Ship it"],
      task: "Build the page from the spec above — for real, in your own words. Then run it through the W3C validator and fix every error. Screenshot the clean validation report; that's your proof of completion.",
      mistake: "Skipping the <head> details (viewport, description) because they're invisible — but they're what make the page work on phones and appear in search. Invisible is not unimportant.",
      tip: "Build it in this order: skeleton → head → header/nav → main content → form → footer → validate. Each step is testable on its own, so a bug is always local to the step you're on.",
      challenge: "Extend the page: add a skills <ul> with two nested sub-lists, and a second external link (opens in a new tab, with rel=\"noopener\"). Re-validate — did anything break, and why?" }
  ]
};
